### ISSUE TITLE
daisy3-to-daisy202: generates invalid ncc.html

### ISSUE THREAD

**Issue by ninkisa** [daisy/pipeline#781]
I'm trying to convert Daisy 3 book to Daisy 2, but some of the metadata tags have empty content
For example:       
In Daisy 3 ncx file the following metadata has content that is not empty
```
      <meta name="dtb:depth" content="1"/>
      <meta name="dtb:maxPageNormal" content="0"/>
```
but in the result ncc.html it is :

```
		<meta content="" name="ncc:depth"/>
		<meta content="" name="ncc:maxPageNormal"/>
```
Also the generated SMIL file has DOCTYPE = http://www.w3.org/TR/REC-smil/SMIL10.dtd which doesn't exists
File not found: http://www.w3.org/TR/REC-smil/SMIL10.dtd

### Expected Behavior
ncc:depth and ncc:maxPageNormal to have correct content attribute
valid SMIL file

### Steps to Reproduce
[Daisy3book.zip](https://github.com/user-attachments/files/15562502/Daisy3book.zip)

Steps taken to reproduce the problem.

1. Extract attached Daisy3book.zip to folder
2. run daisy3-to-daisy202 for the opf file in the extracted folder

### Generated Daisy 2
[generated.D202.zip](https://github.com/user-attachments/files/15565195/generated.D202.zip)

### Environment
* Operating system: Ubuntu 22.04.4 LTS }
* DAISY Pipeline 2 version: 1.14.16
* Interface: command line interface : 2.1.7

### Logs
[output.txt](https://github.com/user-attachments/files/15564908/output.txt)

**Comment by bertfrees** [comment]
Thank you for the report!

**Comment by ninkisa** [comment]
Hello @bertfrees ,

thank you for your support on this issue.
I see that it is fixed in June release and pipeline v1.14.19.
How can I test the change? 
In the assembly project (https://github.com/daisy/pipeline-assembly/releases) there is no release 1.14.19

**Comment by bertfrees** [comment]
The "June" release has actually not been released yet. Please check back in a couple of days, and then 1.14.19 should hopefully be available.

**Comment by bertfrees** [comment]
The other reported issue was not fixed yet:

> Also the generated SMIL file has DOCTYPE = http://www.w3.org/TR/REC-smil/SMIL10.dtd which doesn't exists
File not found: http://www.w3.org/TR/REC-smil/SMIL10.dtd

This has now been fixed locally and I'm sending a snapshot version.
